version: '3.8'

services:
  registrar-jubilacion-app:
    build: .
    container_name: registrar-jubilacion-app
    ports:
      - "3003:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx-registrar-jubilacion
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - registrar-jubilacion-app
